image: python:3.12
stages:
  - build
  - test

build:
  stage: build
  before_script:
    # install dependencies
    - apt update
    - apt install -y nodejs npm
    - python -m pip install -U "jupyterlab>=4.0.0,<5"
    # lint checks
    - set -eux
    - jlpm
    - jlpm run lint:check
  script:
    - set -eux
    - python -m pip install .[test]
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "learning-traces-extension.*OK"
    - python -m jupyterlab.browser_check --allow-root

# test:
#   stage: test
#   script:
#     - set -eux
#     - jlpm run test  
