image: python

.rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never

.dependencies:
  before_script:
    # install dependencies
    - apt update
    - apt install -y nodejs npm
    - python -m pip install -U "jupyterlab>=4.0.0,<5"
    - python -m pip install -U "jupyterlab-pioneer>=1.7.0"

stages:
  - build
  - test


build:
  stage: build
  extends:
    - .rules
    - .dependencies
  script:
    - set -eux
    - python -m pip install .[test]
    - pip install pytest-check-links[cache]
    # lint checks
    - set -eux
    - jlpm
    - jlpm run lint:check
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "learning-traces-extension.*OK"
    # Install dependencies for browser check
    - npx playwright install-deps
    - python -m jupyterlab.browser_check --allow-root
    # Package the extension
    - pip install build
    - python -m build
    # Check links
    - pytest-check-links
  artifacts:
    paths:
      - dist

test:
  stage: test
  extends:
    - .rules
    - .dependencies
  script:
    - set -eux
    - python -m pip install .[test]
    - jlpm run test
